Repository artichoke/www.artichokeruby.org, pull requests merged in 2022-02, with the labels that each got.

#469 Rollup @dependabot npm package updates for February 2022
  package-lock.json
  package.json
Labels: A-deps

#470 chore: Update `.github/workflows/audit.yaml` in `artichoke/www.artich…
  .github/workflows/audit.yaml
Labels: A-build

#471 Remove Google Tag Manager tracking
  src/index.html
  src/install.html
  src/partials/google-analytics-noscript.html
  src/partials/google-analytics.html
Labels: A-webapp, A-project, A-performance

#449 Add i18n framework with zh-hans translation
  build.mjs
  src/index.html
  src/install.html
  src/locales/en.json
  src/locales/zh-hans.json
  src/partials/footer.html
  src/partials/nav.html
Labels: A-webapp, A-project, A-content, A-bundle

#472 Localize title and description tags in HTML head section
  src/index.html
  src/install.html
  src/locales/en.json
  src/locales/zh-hans.json
Labels: A-webapp, A-content

#473 Add a language selector dropdown
  src/index.html
  src/install.html
  src/partials/nav.html
Labels: A-webapp, A-project

#474 Update 'Docker images' section on install page to refer to current container base image versions
  src/locales/en.json
  src/locales/zh-hans.json
Labels: C-bug, A-content

#475 Localize Twitter embeds and meta links
  build.mjs
  src/index.html
  src/install.html
  src/partials/nav.html
Labels: C-quality, A-webapp

#476 Add `rel="alternate"` link tags with `hreflang` to inform search engines of localized content
  build.mjs
  src/index.html
  src/install.html
  src/locales/zh-Hans.json
  src/partials/nav.html
Labels: A-webapp

#477 fix zh-hans site URL path errors
  build.mjs
Labels: C-bug

#478 Fix dropdown aligment in navbar
  src/index.scss
Labels: A-webapp, C-bug
